image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
before_build:
  - dotnet restore
build:
  parallel: true
  project: StrictEmit.sln